<a href="https://colab.research.google.com/github/paulgureghian/Machine_Learning_with_SciKit_Learn_/blob/master/SKLearn_AdaBoost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Created by Paul A. Gureghian in Feb 2019.**

**In this notebook I will introduce the 'AdaBoost' ML algorithm.**

**Its purpose is to combine or 'boost' low accuracy models.**

**Thus creating a high accuracy model.**

**I will use the 'SKLearn' ML library.**

In [0]:
### Import SKLearn
from sklearn import metrics
from sklearn import datasets
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split

In [13]:
### Load 'iris' dataset 
iris = datasets.load_iris()

X = iris.data
y = iris.target

print(X.view, '\n')
print('X:\n', X)

<built-in method view of numpy.ndarray object at 0x7f1c7f250300> 

X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2

In [14]:
### Split the dataset into 'train' and 'test' sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

print('X_train_length:\n', len(X_train), '\n')
print('X_test_length:\n', len(X_test), '\n')
print('y_train_length:\n', len(y_train), '\n')
print('y_test_length:\n', len(y_test)) 

X_train_length:
 105 

X_test_length:
 45 

y_train_length:
 105 

y_test_length:
 45


In [0]:
### Build the AdaBoost model

### Instantiate 'AdaBoost'
Adbc = AdaBoostClassifier(n_estimators=50, learning_rate=1.5)

### Train 'AdaBoost'
model = Adbc.fit(X_train, y_train)

### Get the model predictions
y_pred = model.predict(X_test)  

In [19]:
### Evaluation of the model's predictions 
accuracy = metrics.accuracy_score(y_test, y_pred)

print('Accuracy:', accuracy) 

Accuracy: 0.9333333333333333
